=== docmalloc/gplmt/contrib/tasklist_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="tasklist" type="tasklist" />
<xs:complexType name="tasklist">
  <xs:sequence>
  	<xs:element name="options" minOccurs="0" maxOccurs="1" />
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="sequence" type="sequence" />
      <xs:element name="parallel" type="parallel" />
      <xs:element name="link" type="link" />
      <xs:element name="run" type="run" />
      <xs:element name="run_per_host" type="run_per_host" />      
      <xs:element name="put" type="put" />
      <xs:element name="get" type="get" />
    </xs:choice>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:element name="options">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="target" type="xs:string"/>
      <xs:element name="log_dir" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="link">
  <xs:sequence>
    <xs:element name="task_file" type="xs:string"/>
    <xs:element name="timeout" type="xs:integer"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="sequence">
  <xs:sequence>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
	  <!-- experiment start/stop control -->
	    <xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="start_absolute" type="xs:dateTime"/>
	    	<xs:element name="start_relative" type="xs:duration"/>
	    </xs:choice>
	    <xs:choice minOccurs="0" maxOccurs="1">
	    	<xs:element name="stop_absolute" type="xs:dateTime"/>
	    	<xs:element name="stop_relative" type="xs:duration"/>
	    </xs:choice>
	  <!-- experiment start/stop control -->
	  <xs:choice minOccurs="0" maxOccurs="unbounded">
	    	<xs:element name="node" type="xs:string"/>
      </xs:choice>  

	  <xs:element name="sequence" type="sequence" />
	  <xs:element name="parallel" type="parallel" />
	  <xs:element name="link" type="link" />
	  <xs:element name="run" type="run" />
	  <xs:element name="run_per_host" type="run_per_host" />      
	  <xs:element name="put" type="put" />
	  <xs:element name="get" type="get" />
    </xs:choice>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="parallel">
  <xs:sequence>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
		<!-- experiment start/stop control -->
	    <xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="start_absolute" type="xs:dateTime"/>
	    	<xs:element name="start_relative" type="xs:duration"/>
	    </xs:choice>
	    <xs:choice minOccurs="0" maxOccurs="1">
	    	<xs:element name="stop_absolute" type="xs:dateTime"/>
	    	<xs:element name="stop_relative" type="xs:duration"/>
	    </xs:choice>
		<!-- experiment start/stop control -->
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="node" type="xs:string"/>
		</xs:choice>
		<xs:element name="sequence" type="sequence" />
		<xs:element name="parallel" type="parallel" />
		<xs:element name="link" type="link" />
		<xs:element name="run" type="run" />
		<xs:element name="run_per_host" type="run_per_host" />
		<xs:element name="put" type="put" />
		<xs:element name="get" type="get" />
    </xs:choice>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="run">
  <xs:sequence>
    <!-- experiment start/stop control -->
	    <xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="start_absolute" type="xs:dateTime"/>
	    	<xs:element name="start_relative" type="xs:duration"/>
	    </xs:choice>
	    <xs:choice minOccurs="0" maxOccurs="1">
	    	<xs:element name="stop_absolute" type="xs:dateTime"/>
	    	<xs:element name="stop_relative" type="xs:duration"/>
	    </xs:choice>
	<!-- experiment start/stop control -->    
    
	<xs:choice minOccurs="0" maxOccurs="unbounded">
	    	<xs:element name="node" type="xs:string"/>
    </xs:choice>

	<xs:element name="command" type="xs:string"/>
    <xs:element name="arguments" type="xs:string"/>
    <xs:element name="timeout" type="xs:integer"/>
    <xs:element name="expected_return_code"  type="xs:integer"/>
    <xs:element name="expected_output" type="xs:string"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:integer"/>  
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="run_per_host">
  <xs:sequence>
    <!-- experiment start/stop control -->
	    <xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="start_absolute" type="xs:dateTime"/>
	    	<xs:element name="start_relative" type="xs:duration"/>
	    </xs:choice>
	    <xs:choice minOccurs="0" maxOccurs="1">
	    	<xs:element name="stop_absolute" type="xs:dateTime"/>
	    	<xs:element name="stop_relative" type="xs:duration"/>
	    </xs:choice>
	<!-- experiment start/stop control -->    

    <xs:element name="command_file" type="xs:string"/>
    <xs:element name="output_prefix" type="xs:string"/>
    <xs:element name="timeout" type="xs:integer"/>
    <xs:element name="expected_return_code"  type="xs:integer"/>
    <xs:element name="expected_output" type="xs:string"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:integer"/>  
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="put">
  <xs:sequence>
    <xs:element name="source" type="xs:string"/>
    <xs:element name="destination" type="xs:string"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:integer"/>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="get">
  <xs:sequence>    
    <xs:element name="source" type="xs:string"/>
    <xs:element name="destination" type="xs:string"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:integer"/>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

</xs:schema>

=== docmalloc/gplmt/contrib/tasklists/install_buildslave_fc8.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Install buildslave" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
	
	<run id="0" name="check peer">
		<!-- Check if peer is working -->
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>30</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output>2013</expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run> 


	<sequence enabled="true">
	<!-- Install dependencies -->
	<run id="1" name="Install gcc">
          <command>sudo yum -y -t --nogpgcheck install</command> 
          <arguments>gcc</arguments> 
          <timeout>0</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
    </run>
	<run id="1" name="Install python distribute">
          <command>curl http://python-distribute.org/distribute_setup.py | sudo python</command> 
          <arguments></arguments> 
          <timeout>0</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
    </run>
	<run id="2" name="Download zope.interface 3.8.0">
          <command>mkdir ~/buildslave; cd ~/buildslave; wget</command> 
          <arguments>http://pypi.python.org/packages/source/z/zope.interface/zope.interface-3.8.0.tar.gz#md5=8ab837320b4532774c9c89f030d2a389n</arguments> 
          <timeout>0</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
    </run>
    <run id="3" name="Unpack zope.interface 3.8.0">
          <command>cd ~/buildslave; tar xfvz </command> 
          <arguments>zope.interface-3.8.0.tar.gz</arguments> 
          <timeout>0</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
    </run>      
    <run id="4" name="Install zope.interface 3.8.0">
          <command>cd ~/buildslave/zope.interface-3.8.0/; sudo python </command> 
          <arguments>setup.py install</arguments> 
          <timeout>0</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
    </run>
    <sequence enabled="true">
	<run id="5" name="Download twisted 12.1.0">
          <command>mkdir ~/buildslave; cd ~/buildslave; wget</command> 
          <arguments>http://pypi.python.org/packages/source/T/Twisted/Twisted-12.1.0.tar.bz2</arguments> 
          <timeout>0</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
    </run>
    <run id="6" name="Unpack twisted 12.1.0">
          <command>cd ~/buildslave; tar jvxf </command> 
          <arguments>Twisted-12.1.0.tar.bz2</arguments> 
          <timeout>0</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
    </run>      
    <run id="7" name="Install twisted 12.1.0">
          <command>cd ~/buildslave/Twisted-12.1.0/; sudo python </command> 
          <arguments>setup.py install</arguments> 
          <timeout>0</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
    </run>    
    </sequence>
    </sequence>
    
    <sequence enabled="true">
    <run id="8" name="Download buildslave">
          <command>cd ~/buildslave; wget </command> 
          <arguments>http://buildbot.googlecode.com/files/buildbot-slave-0.8.6p1.tar.gz</arguments> 
          <timeout>0</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
    </run>
    <run id="9" name="Unpack buildslave">
          <command>cd ~/buildslave; tar xvfz </command> 
          <arguments>buildbot-slave-0.8.6p1.tar.gz</arguments> 
          <timeout>0</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
    </run>
     <run id="10" name="Install buildslave">
          <command>cd ~/buildslave/buildbot-slave-0.8.6p1; sudo python setup.py </command> 
          <arguments>install</arguments> 
          <timeout>0</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
    </run>        
    </sequence>	    
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/deploy_zabbix_agent.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Deploy zabbix agent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
	
	<run id="0" name="check peer">
		<!-- Check if peer is working -->
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output>2013</expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run>
	
	<sequence enabled="true">
	    <run id="0" name="kill any running zabbix agent">
            <command>killall</command> 
            <arguments>zabbix_agentd</arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="1" name="create zabbix directory">
            <command>mkdir</command> 
            <arguments>zabbix</arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>

	    <run id="2" name="download source 2.0.4">
            <command>cd zabbix; wget</command> 
            <arguments>http://iweb.dl.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/2.0.4/zabbix-2.0.4.tar.gz</arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	
	    <run id="3" name="unzip source">
            <command>cd zabbix; tar -xvzf</command> 
            <arguments>zabbix-2.0.4.tar.gz</arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	
	    <run id="4" name="configure">
            <command>cd zabbix/zabbix-2.0.4; ./configure --enable-agent</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	
	    <run id="5" name="install make">
            <command>sudo yum -y -t --nogpgcheck install</command> 
            <arguments>make</arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	
	    <run id="6" name="make install">
            <command>cd zabbix/zabbix-2.0.4; sudo make install</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	
	    <run id="7" name="create /etc/zabbix dir">
            <command>sudo mkdir</command> 
            <arguments>/etc/zabbix/</arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	
	    <put id="8" name="put zabbix_agentd.conf">
		    <source>contrib/zabbix_agentd.conf</source>
		    <destination>~/zabbix/zabbix_agentd.conf</destination>
		    <stop_on_fail>false</stop_on_fail>
	    </put>
	
	    <run id="9" name="move conf file">
            <command>sudo mv zabbix/zabbix_agentd.conf</command> 
            <arguments>~/zabbix_agentd.conf</arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	
	    <run id="10" name="start agent">
            <command>/usr/local/sbin/zabbix_agentd -c ~/zabbix_agentd.conf</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>true</stop_on_fail>
	    </run>
    </sequence>
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/update_crypto.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Install libgcrypt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
	
	<run id="0" name="check peer">
		<!-- Check if peer is working -->
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output>2013</expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run>
	
	<sequence enabled="true">
	    <run id="0" name="Update M4 (1)">
            <command>sudo rpm -e --nodeps m4</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="1" name="Update M4 (2)">
            <command>wget http://ftp.gnu.org/gnu/m4/m4-latest.tar.gz</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="2" name="Update M4 (3)">
            <command>tar xfvz m4-latest.tar.gz</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="3" name="Update M4 (4)">
            <command>cd m4-1.4.16; ./configure --prefix=/usr</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="4" name="Update M4 (5)">
            <command>cd m4-1.4.16; sudo make install</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="5" name="Update autoconf (1)">
            <command>sudo rpm -e --nodeps autoconf</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="6" name="Update autoconf (2)">
            <command>wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="7" name="Update autoconf (3)">
            <command>tar xfvz autoconf-2.69.tar.gz</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="8" name="Update autoconf (4)">
            <command>cd autoconf-2.69; ./configure --prefix=/usr</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="9" name="Update autoconf (5)">
            <command>cd autoconf-2.69; sudo make install</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="10" name="Install git">
            <command>sudo yum install -y -t --nogpgcheck git</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="11" name="fig (1)">
            <command>sudo touch /usr/bin/fig2dev</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="12" name="fig (2)">
            <command>sudo chmod u+x /usr/bin/fig2dev</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="13" name="Install libgcrypt (1)">
            <command>git clone git://git.gnupg.org/libgcrypt.git libgcrypt.git</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="14" name="Install libgcrypt (2)">
            <command>cd libgcrypt.git; ./autogen.sh</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="15" name="Install libgcrypt (3)">
            <command>cd libgcrypt.git;  ./configure --enable-maintainer-mode --prefix=$HOME/libgcrypt-dev</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="16" name="Install libgcrypt (4)">
            <command>cd libgcrypt.git; sudo make</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="17" name="Install libgcrypt (5)">
            <command>cd libgcrypt.git; sudo make install</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="18" name="Install libgcrypt (6)">
            <command>cd libgcrypt.git; sudo make install</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>true</stop_on_fail>
	    </run>
    </sequence>
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/example_start_relative.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Example task list with a task starting 3 minutes after experiment was started and is running for 5 minutes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
	<run id="0" name="get date">
		<start_relative>P3M</start_relative>
		<stop_relative>P5M</stop_relative>
        <command></command> 
        <arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run> 
</tasklist>

=== docmalloc/gplmt/contrib/simpletasks.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Simple task list" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
	<run id="0" name="get date">
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run> 
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/start_buildslaves.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Start buildslaves on Planetlab nodes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
	<run id="0" name="check peer">
		<!-- Check if peer is working -->
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output>2013</expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run> 
		<run id="2" name="start buildslave" enabled="true">
		<command>buildslave</command>
		<arguments>start ./bot</arguments> 
        <timeout>60</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>false</stop_on_fail>
    </run>	
</tasklist>
