=== docmalloc/gplmt/contrib/tasklist_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="tasklist" type="tasklist" />
<xs:complexType name="tasklist">
  <xs:sequence>
  	<xs:element name="options" minOccurs="0" maxOccurs="1" />
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="sequence" type="sequence" />
      <xs:element name="parallel" type="parallel" />
      <xs:element name="link" type="link" />
      <xs:element name="run" type="run" />
      <xs:element name="run_per_host" type="run_per_host" />      
      <xs:element name="put" type="put" />
      <xs:element name="get" type="get" />
    </xs:choice>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:element name="options">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="target" type="xs:string"/>
      <xs:element name="log_dir" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="link">
  <xs:sequence>
    <xs:element name="task_file" type="xs:string"/>
    <xs:element name="timeout" type="xs:integer"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="sequence">
  <xs:sequence>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
	  <!-- experiment start/stop control -->
	    <xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="start_absolute" type="xs:dateTime"/>
	    	<xs:element name="start_relative" type="xs:duration"/>
	    </xs:choice>
	    <xs:choice minOccurs="0" maxOccurs="1">
	    	<xs:element name="stop_absolute" type="xs:dateTime"/>
	    	<xs:element name="stop_relative" type="xs:duration"/>
	    </xs:choice>
	  <!-- experiment start/stop control -->
	  <xs:choice minOccurs="0" maxOccurs="unbounded">
	    	<xs:element name="node" type="xs:string"/>
      </xs:choice>  

	  <xs:element name="sequence" type="sequence" />
	  <xs:element name="parallel" type="parallel" />
	  <xs:element name="link" type="link" />
	  <xs:element name="run" type="run" />
	  <xs:element name="run_per_host" type="run_per_host" />      
	  <xs:element name="put" type="put" />
	  <xs:element name="get" type="get" />
    </xs:choice>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="parallel">
  <xs:sequence>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
		<!-- experiment start/stop control -->
	    <xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="start_absolute" type="xs:dateTime"/>
	    	<xs:element name="start_relative" type="xs:duration"/>
	    </xs:choice>
	    <xs:choice minOccurs="0" maxOccurs="1">
	    	<xs:element name="stop_absolute" type="xs:dateTime"/>
	    	<xs:element name="stop_relative" type="xs:duration"/>
	    </xs:choice>
		<!-- experiment start/stop control -->
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="node" type="xs:string"/>
		</xs:choice>
		<xs:element name="sequence" type="sequence" />
		<xs:element name="parallel" type="parallel" />
		<xs:element name="link" type="link" />
		<xs:element name="run" type="run" />
		<xs:element name="run_per_host" type="run_per_host" />
		<xs:element name="put" type="put" />
		<xs:element name="get" type="get" />
    </xs:choice>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="run">
  <xs:sequence>
    <!-- experiment start/stop control -->
	    <xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="start_absolute" type="xs:dateTime"/>
	    	<xs:element name="start_relative" type="xs:duration"/>
	    </xs:choice>
	    <xs:choice minOccurs="0" maxOccurs="1">
	    	<xs:element name="stop_absolute" type="xs:dateTime"/>
	    	<xs:element name="stop_relative" type="xs:duration"/>
	    </xs:choice>
	<!-- experiment start/stop control -->    
    
	<xs:choice minOccurs="0" maxOccurs="unbounded">
	    	<xs:element name="node" type="xs:string"/>
    </xs:choice>

	<xs:element name="command" type="xs:string"/>
    <xs:element name="arguments" type="xs:string"/>
    <xs:element name="timeout" type="xs:integer"/>
    <xs:element name="expected_return_code"  type="xs:integer"/>
    <xs:element name="expected_output" type="xs:string"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:integer"/>  
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="run_per_host">
  <xs:sequence>
    <!-- experiment start/stop control -->
	    <xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="start_absolute" type="xs:dateTime"/>
	    	<xs:element name="start_relative" type="xs:duration"/>
	    </xs:choice>
	    <xs:choice minOccurs="0" maxOccurs="1">
	    	<xs:element name="stop_absolute" type="xs:dateTime"/>
	    	<xs:element name="stop_relative" type="xs:duration"/>
	    </xs:choice>
	<!-- experiment start/stop control -->    

    <xs:element name="command_file" type="xs:string"/>
    <xs:element name="output_prefix" type="xs:string"/>
    <xs:element name="timeout" type="xs:integer"/>
    <xs:element name="expected_return_code"  type="xs:integer"/>
    <xs:element name="expected_output" type="xs:string"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:integer"/>  
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="put">
  <xs:sequence>
    <xs:element name="source" type="xs:string"/>
    <xs:element name="destination" type="xs:string"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:integer"/>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="get">
  <xs:sequence>    
    <xs:element name="source" type="xs:string"/>
    <xs:element name="destination" type="xs:string"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:integer"/>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

</xs:schema>

=== docmalloc/gplmt/contrib/tasklists/zabbix_crontab.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Start zabbix agent on reboot (crontab)" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
	
	<run id="0" name="check peer">
		<!-- Check if peer is working -->
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output>2013</expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run>
	
	<sequence enabled="true">
	    <run id="0" name="Add tumple_gnunet to allow list">
            <command>echo tumple_gnunet | sudo tee -a /etc/cron.allow</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
	    
	    <run id="1" name="add reboot entry to crontab file">
            <command>echo "@reboot /usr/local/sbin/zabbix_agentd -c ~/zabbix_agentd.conf" | sudo tee -a /var/spool/cron/tumple_gnunet</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>true</stop_on_fail>
	    </run>

	    <run id="2" name="start crontab service">
            <command>sudo /etc/init.d/crond start</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>true</stop_on_fail>
	    </run>
    </sequence>
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/install_gnurl.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Install gnurl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
	
<run id="0" name="check peer">
	<command>sudo date</command> 
	<arguments></arguments> 
	<timeout>10</timeout>
	<expected_return_code>0</expected_return_code>
	<expected_output>2013</expected_output>
	<stop_on_fail>true</stop_on_fail>
</run> 


<run id="1" name="Download gnurl" enabled="false">
          <command>wget</command> 
          <arguments>https://gnunet.org/sites/default/files/gnurl-7.33.0.tar_0.bz2</arguments> 
          <timeout>30</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
</run>
<run id="2" name="Unpack">
          <command>tar xf</command> 
          <arguments>gnurl-7.33.0.tar_0.bz2</arguments> 
          <timeout>30</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
</run>
<run id="3" name="Configure">
          <command>cd gnurl-7.33.0; ./configure </command> 
          <arguments>--prefix=/usr --enable-ipv6 --with-gnutls --without-libssh2 --without-libmetalink --without-winidn --without-librtmp --without-nghttp2 --without-nss --without-cyassl --without-polarssl --without-ssl --without-winssl --without-darwinssl --disable-sspi --disable-ntlm-wb --disable-ldap --disable-rtsp --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-file --disable-ftp</arguments> 
          <timeout>90</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>true</stop_on_fail>
</run>
<run id="4" name="Install">
          <command>cd gnurl-7.33.0; make install </command> 
          <arguments></arguments> 
          <timeout>120</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail></stop_on_fail>
</run>
	
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/planetlab/planetlab_check_libgcrypt_version.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Check libgcrypt version" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../tasklist_schema.xsd">
	<options>
 	<target>planetlab</target>
 	<log_dir></log_dir>>
 	</options>

	<run id="0" name="check peer">
		<!-- Check if peer is working -->
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output>2013</expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run>

	<sequence name="Check libgcrypt version" enabled="true">
		<run id="91" name="Checking version">
		    <command>libgcrypt-config --version</command> 
		    <arguments></arguments> 
		    <timeout>0</timeout> 
		    <expected_return_code>0</expected_return_code>
		    <expected_output>1.6.0</expected_output>
		    <stop_on_fail>true</stop_on_fail>
		</run>	
    </sequence>
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/Install_gcrypt-1.6.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd" name="Install gcrypt-1.6.0">
  <options/>
  <sequence name="Stop if libgcrypt is already installed" enabled="true">
    <run name="Check if /usr/local/lib/libgcrypt.so.20 exits and stop if it does" id="1" enabled="true">
      <command>stat /usr/local/lib/libgcrypt.so.20</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>1</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
  </sequence>
  <sequence name="Check and install GCC if not present" enabled="true">
    <run name="Check and install gcc and make" id="1" enabled="true">
      <command>which gcc || sudo -S yum -y -t --nogpgcheck install gcc &amp;&amp; sudo -S yum -y -t --nogpgcheck install make</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
  </sequence>
  <sequence name="" enabled="true">
    <run name="Prepare build dir and download libgpg-error" id="1" enabled="true">
      <command>mkdir libgpg-error; cd libgpg-error; wget ftp://ftp.gnupg.org/gcrypt/libgpg-error/libgpg-error-1.12.tar.bz2</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Unbundle libgpg-error-1.12" id="2" enabled="true">
      <command>cd libgpg-error; tar xaf libgpg-error-1.12.tar.bz2</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Configure libgpg-error-1.12" id="3" enabled="true">
      <command>cd libgpg-error/libgpg-error-1.12; ./configure --prefix=/usr/local</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Compile and Install libgpg-error-1.12" id="4" enabled="true">
      <command>cd libgpg-error/libgpg-error-1.12; make &amp;&amp; sudo -S make install</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
  </sequence>
  <sequence name="Install libgcrypt-1.6.1" enabled="true">
    <run name="Prepare libgcrypt build dir and download source" id="1" enabled="true">
      <command>mkdir libgcrypt; cd libgcrypt; wget</command>
      <arguments>ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.6.1.tar.bz2</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Unpack" id="2" enabled="true">
      <command>cd libgcrypt; tar xaf libgcrypt-1.6.1.tar.bz2</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Configure libgcrypt-1.6.1" id="3" enabled="true">
      <command>cd libgcrypt/libgcrypt-1.6.1; ./configure --prefix=/usr/local --with-libgpg-error=/usr/local</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Compile and install" id="4" enabled="true">
      <command>cd libgcrypt/libgcrypt-1.6.1; make &amp;&amp; sudo -S make install</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
  </sequence>
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/gnunet_nse_histograms.xml
<?xml version="1.0" encoding="UTF-8"?> 
<tasklist
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd"
    name="Configure NSE histograms">
  <options/>
    <sequence name="" enabled="true">
    <run name="Download GNUnet" id="1" enabled="true">
      <command>svn checkout</command>
      <arguments>https://gnunet.org/svn/gnunet</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Bootstrap GNUnet" id="2" enabled="true">
      <command>cd gnunet; libtoolize; ./bootstrap</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Configure GNUnet" id="3" enabled="true">
      <command>cd gnunet; ./configure</command>
      <arguments> --with-extractor=/usr/local --with-libgcrypt-prefix=/usr/local --with-mysql=/usr/lib/mysql --enable-logging=verbose --enable-nse-histogram=yes --disable-autostart --with-libgnurl=/usr/local
      </arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Install GNUnet" id="4" enabled="true">
      <command>cd gnunet; sudo -S make install</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
  </sequence>
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/Test_GUIX.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd" name="Test GUIX">
  <options/>
  <run name="Run daemon and install hello" id="1" enabled="true">
    <command>sudo -S `which guix-daemon` --build-users-group=guix-builder --disable-chroot &amp; guix package --verbose -i hello</command>
    <arguments></arguments>
    <timeout>0</timeout>
    <expected_return_code>0</expected_return_code>
    <expected_output></expected_output>
    <stop_on_fail>true</stop_on_fail>
  </run>
  <run name="Run hello" id="2" enabled="true">
    <command>hello</command>
    <arguments></arguments>
    <timeout>0</timeout>
    <expected_return_code>0</expected_return_code>
    <expected_output></expected_output>
    <stop_on_fail>true</stop_on_fail>
  </run>
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/setup_buildslaves.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Setup buildslave on Planetlab nodes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
	<run id="0" name="check peer">
		<!-- Check if peer is working -->
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output>2013</expected_output>
        <stop_on_fail>false</stop_on_fail>
	</run> 
	
	<run id="2" name="Delete old configuration">
		<command>rm -rf bot</command>
		<arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>false</stop_on_fail>		
	</run>  
	
	<run_per_host id="1" name="setup buildslave">
		<command_file>/home/mwachs/repositories/pltestbed/slave_deployment_cmds</command_file>
		<output_prefix>contrib/tests/result_</output_prefix>
        <timeout>30</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>true</stop_on_fail>		
	</run_per_host>
	<run id="2" name="start buildslave">
		<command>buildslave start ./bot</command>
		<arguments></arguments> 
        <timeout>60</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>true</stop_on_fail>		
	</run>  
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/check_node.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Check if peer can is accessible" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
   	<sequence  enabled="true">
	<run id="0" name="check peer">
		<!-- Check if peer is working -->
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output>2013</expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run> 
    </sequence>    	
</tasklist>
