=== docmalloc/gplmt/contrib/tasklist_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="tasklist" type="tasklist" />
<xs:complexType name="tasklist">
  <xs:sequence>
  	<xs:element name="options" minOccurs="0" maxOccurs="1" />
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="sequence" type="sequence" />
      <xs:element name="parallel" type="parallel" />
      <xs:element name="link" type="link" />
      <xs:element name="run" type="run" />
      <xs:element name="run_per_host" type="run_per_host" />      
      <xs:element name="put" type="put" />
      <xs:element name="get" type="get" />
    </xs:choice>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:element name="options">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="target" type="xs:string"/>
      <xs:element name="log_dir" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="link">
  <xs:sequence>
    <xs:element name="task_file" type="xs:string"/>
    <xs:element name="timeout" type="xs:integer"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="sequence">
  <xs:sequence>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
	  <!-- experiment start/stop control -->
	    <xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="start_absolute" type="xs:dateTime"/>
	    	<xs:element name="start_relative" type="xs:duration"/>
	    </xs:choice>
	    <xs:choice minOccurs="0" maxOccurs="1">
	    	<xs:element name="stop_absolute" type="xs:dateTime"/>
	    	<xs:element name="stop_relative" type="xs:duration"/>
	    </xs:choice>
	  <!-- experiment start/stop control -->
	  <xs:choice minOccurs="0" maxOccurs="unbounded">
	    	<xs:element name="node" type="xs:string"/>
      </xs:choice>  

	  <xs:element name="sequence" type="sequence" />
	  <xs:element name="parallel" type="parallel" />
	  <xs:element name="link" type="link" />
	  <xs:element name="run" type="run" />
	  <xs:element name="run_per_host" type="run_per_host" />      
	  <xs:element name="put" type="put" />
	  <xs:element name="get" type="get" />
    </xs:choice>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="parallel">
  <xs:sequence>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
		<!-- experiment start/stop control -->
	    <xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="start_absolute" type="xs:dateTime"/>
	    	<xs:element name="start_relative" type="xs:duration"/>
	    </xs:choice>
	    <xs:choice minOccurs="0" maxOccurs="1">
	    	<xs:element name="stop_absolute" type="xs:dateTime"/>
	    	<xs:element name="stop_relative" type="xs:duration"/>
	    </xs:choice>
		<!-- experiment start/stop control -->
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="node" type="xs:string"/>
		</xs:choice>
		<xs:element name="sequence" type="sequence" />
		<xs:element name="parallel" type="parallel" />
		<xs:element name="link" type="link" />
		<xs:element name="run" type="run" />
		<xs:element name="run_per_host" type="run_per_host" />
		<xs:element name="put" type="put" />
		<xs:element name="get" type="get" />
    </xs:choice>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="run">
  <xs:sequence>
    <!-- experiment start/stop control -->
	    <xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="start_absolute" type="xs:dateTime"/>
	    	<xs:element name="start_relative" type="xs:duration"/>
	    </xs:choice>
	    <xs:choice minOccurs="0" maxOccurs="1">
	    	<xs:element name="stop_absolute" type="xs:dateTime"/>
	    	<xs:element name="stop_relative" type="xs:duration"/>
	    </xs:choice>
	<!-- experiment start/stop control -->    
    
	<xs:choice minOccurs="0" maxOccurs="unbounded">
	    	<xs:element name="node" type="xs:string"/>
    </xs:choice>

	<xs:element name="command" type="xs:string"/>
    <xs:element name="arguments" type="xs:string"/>
    <xs:element name="timeout" type="xs:integer"/>
    <xs:element name="expected_return_code"  type="xs:integer"/>
    <xs:element name="expected_output" type="xs:string"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:integer"/>  
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="run_per_host">
  <xs:sequence>
    <!-- experiment start/stop control -->
	    <xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="start_absolute" type="xs:dateTime"/>
	    	<xs:element name="start_relative" type="xs:duration"/>
	    </xs:choice>
	    <xs:choice minOccurs="0" maxOccurs="1">
	    	<xs:element name="stop_absolute" type="xs:dateTime"/>
	    	<xs:element name="stop_relative" type="xs:duration"/>
	    </xs:choice>
	<!-- experiment start/stop control -->    

    <xs:element name="command_file" type="xs:string"/>
    <xs:element name="output_prefix" type="xs:string"/>
    <xs:element name="timeout" type="xs:integer"/>
    <xs:element name="expected_return_code"  type="xs:integer"/>
    <xs:element name="expected_output" type="xs:string"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:integer"/>  
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="put">
  <xs:sequence>
    <xs:element name="source" type="xs:string"/>
    <xs:element name="destination" type="xs:string"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:integer"/>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="get">
  <xs:sequence>    
    <xs:element name="source" type="xs:string"/>
    <xs:element name="destination" type="xs:string"/>
    <xs:element name="stop_on_fail" type="xs:boolean"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:integer"/>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

</xs:schema>

=== docmalloc/gplmt/contrib/tasklists/Install_GUIX_Fedora_14.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd" name="Install GUIX Fedora 14">
  <options/>
  <sequence name="Installing Guile (dependency)" enabled="true">
    <run name="Installing gcc" id="1" enabled="true">
      <command>sudo -S yum -y -t --nogpgcheck install</command>
      <arguments>gcc</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Installing libtool" id="2" enabled="true">
      <command>sudo -S yum -y -t --nogpgcheck install</command>
      <arguments>libtool</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Installing libltdl" id="3" enabled="true">
      <command>sudo -S yum -y -t --nogpgcheck install</command>
      <arguments>libtool-ltdl-devel</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Installing GNU MP" id="4" enabled="true">
      <command>sudo -S yum -y -t --nogpgcheck install</command>
      <arguments>gmp-devel</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Installing libunistring" id="5" enabled="true">
      <command>sudo -S yum -y -t --nogpgcheck install</command>
      <arguments>libunistring-devel</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Installing libffi" id="6" enabled="true">
      <command>sudo -S yum -y -t --nogpgcheck install</command>
      <arguments>libffi-devel</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Installing libgc" id="7" enabled="true">
      <command>sudo -S yum -y -t --nogpgcheck install</command>
      <arguments>gc-devel</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Installing make" id="8" enabled="true">
      <command>sudo -S yum -y -t --nogpgcheck install</command>
      <arguments>make</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Get Guile" id="9" enabled="true">
      <command>wget</command>
      <arguments>ftp://ftp.gnu.org/gnu/guile/guile-2.0.5.tar.gz</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Export guile archive" id="10" enabled="true">
      <command>tar xvzf</command>
      <arguments>guile-2.0.5.tar.gz</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Configure guile" id="11" enabled="true">
      <command>cd guile-2.0.5; ./configure</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Make guile" id="12" enabled="true">
      <command>cd guile-2.0.5; make</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="Install guile" id="13" enabled="true">
      <command>cd guile-2.0.5; sudo -S make install</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
  </sequence>
  <sequence name="Other GUIX dependencies" enabled="true">
    <run name="install libgcrypt" id="1" enabled="true">
      <command>sudo -S yum -y -t --nogpgcheck install</command>
      <arguments>libgcrypt-devel</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="install 1sqlite3" id="2" enabled="true">
      <command>sudo -S yum -y -t --nogpgcheck install</command>
      <arguments>libsqlite3x-devel</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="install libbz2" id="3" enabled="true">
      <command>sudo -S yum -y -t --nogpgcheck install</command>
      <arguments>bzip2-devel</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="install g++" id="4" enabled="true">
      <command>sudo -S yum -y -t --nogpgcheck install</command>
      <arguments>gcc-c++</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
  </sequence>
  <sequence name="GUIX installation" enabled="true">
    <run name="get guix" id="1" enabled="true">
      <command>wget</command>
      <arguments>https://gnunet.org/eclectic/guix-0.6.tar.gz</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="export archive" id="2" enabled="true">
      <command>tar xvzf</command>
      <arguments>guix-0.6.tar.gz</arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="configure" id="3" enabled="true">
      <command>export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig; cd guix-0.6; ./configure</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="make" id="4" enabled="true">
      <command>cd guix-0.6; make</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="make install" id="5" enabled="true">
      <command>cd guix-0.6; sudo -S make install</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
  </sequence>
  <sequence name="GUIX configuration" enabled="true">
    <run name="create builder group" id="1" enabled="true">
      <command>sudo -S groupadd guix-builder</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="create builders" id="2" enabled="true">
      <command>for i in `seq 1 10`; do sudo -S useradd -g guix-builder -G guix-builder -d /var/empty -s `which nologin` -c "Guix build user $i" guix-builder$i; done</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="create necessary directories" id="3" enabled="true">
      <command>sudo -S mkdir -p /usr/local/var/nix/profiles/per-user; sudo -S chmod 777 /usr/local/var/nix/profiles/per-user; sudo -S mkdir -p /nix/store; sudo -S chgrp 504 /nix/store; sudo -S chmod 1775 /nix/store</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
    <run name="add guix bin to path" id="4" enabled="true">
      <command>echo 'export PATH=$PATH:$HOME/.guix-profile/bin' &gt;&gt; .bash_profile</command>
      <arguments></arguments>
      <timeout>0</timeout>
      <expected_return_code>0</expected_return_code>
      <expected_output></expected_output>
      <stop_on_fail>true</stop_on_fail>
    </run>
  </sequence>
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/test_sftp_tasks.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="remote put/get test task list" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
	<put id="0" name="put testfile">
		<source>/tmp/test.file</source>
		<destination>/tmp/put.file</destination>
		<stop_on_fail>true</stop_on_fail>
	</put> 
	<get id="1" name="get testfile">
		<source>/tmp/put.file</source>
		<destination>/tmp/</destination>
		<stop_on_fail>true</stop_on_fail>
	</get> 
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/test_tasks.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Tasklist example" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
  <task>
        <id>0</id>
        <name>run 1</name>
        <type>run</type> 
        <command>ls</command> 
        <arguments></arguments>
        <timeout>10</timeout> 
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>0</stop_on_fail>
    </task> 
    <parallel>
      <task>
        <id>1</id>
        <name>run p2a</name>
        <type>run</type> 
        <command>date</command> 
        <arguments></arguments> 
        <timeout>30</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>0</stop_on_fail>
    </task> 
      <task>
        <id>2</id>
        <name>run p2b</name>
        <type>run</type> 
        <command>ls</command> 
        <arguments></arguments> 
        <timeout>30</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>0</stop_on_fail>
    </task>     
    </parallel>
    <sequence>
      <task>
        <id>3</id>
        <name>run 3</name>
        <type>run</type> 
        <command>date</command> 
        <arguments></arguments> 
        <timeout>30</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>0</stop_on_fail>
	  </task>
	   <task>
        <id>4</id>
        <name>run 4</name>
        <type>run</type> 
        <command>date</command> 
        <arguments></arguments> 
        <timeout>30</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>0</stop_on_fail>
	  </task>
    </sequence> 
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/deploy_gnunet_conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Deploy GNUnet configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
<sequence  enabled="true">
	<run id="0" name="check peer">
		<!-- Check if peer is working -->
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>30</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output>2013</expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run>
     <run id="0" name="remove old config">
		<!-- Remove -->
        <command>sudo rm</command> 
        <arguments>/home/tumple_gnunet/.gnunet/gnunet.conf</arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>false</stop_on_fail>
	</run>
     <run id="1" name="create directory">
		<!-- Remove -->
        <command>mkdir</command> 
        <arguments>/home/tumple_gnunet/.gnunet</arguments> 
        <timeout>10</timeout>
        <expected_return_code>-1</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>false</stop_on_fail>
	</run>
     <run id="1" name="create directory">
		<!-- Remove -->
        <command>mkdir</command> 
        <arguments>/home/tumple_gnunet/logs</arguments> 
        <timeout>10</timeout>
        <expected_return_code>-1</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>false</stop_on_fail>
	</run>	
	<put id="2" name="put gnunet.conf">
		<source>contrib/gnunet.conf</source>
		<destination>/home/tumple_gnunet/.gnunet/gnunet.conf</destination>
		<stop_on_fail>true</stop_on_fail>
	</put> 
</sequence>    	
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/test_run_per_host_tasks.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Test run_per_host tasks" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
	<run id="0" name="check peer">
		<!-- Check if peer is working -->
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output>2013</expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run> 
	<run_per_host id="1" name="get hostname">
		<command_file>contrib/tasklists/tests/test_run_per_host.cmds</command_file>
		<output_prefix>contrib/tests/result_</output_prefix>
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>true</stop_on_fail>		
	</run_per_host> 
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/update_zabbix_agent_conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Deploy zabbix agent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../tasklist_schema.xsd">
	
	<run id="0" name="check peer">
		<!-- Check if peer is working -->
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output>2013</expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run>
	
	<sequence enabled="true">
	    <run id="1" name="kill any running zabbix agent">
            <command>killall</command> 
            <arguments>zabbix_agentd</arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>false</stop_on_fail>
	    </run>
		<put id="2" name="put gnunet.conf">
			<source>contrib/zabbix_agentd.conf</source>
			<destination>/home/tumple_gnunet/zabbix_agentd.conf</destination>
			<stop_on_fail>true</stop_on_fail>
		</put> 
		
		<run id="10" name="start agent">
            <command>/usr/local/sbin/zabbix_agentd -c ~/zabbix_agentd.conf</command> 
            <arguments></arguments> 
            <timeout>0</timeout>
            <expected_return_code>0</expected_return_code>
            <expected_output></expected_output>
            <stop_on_fail>true</stop_on_fail>
	    </run>
    </sequence>
</tasklist>

=== docmalloc/gplmt/contrib/tasklists/planetlab/planetlab_install_gnunet.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasklist name="Install GNUnet on PlanetLab node" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../tasklist_schema.xsd">
	
	<run id="0" name="check peer">
		<!-- Check if peer is working -->
        <command>sudo date</command> 
        <arguments></arguments> 
        <timeout>10</timeout>
        <expected_return_code>0</expected_return_code>
        <expected_output>2013</expected_output>
        <stop_on_fail>true</stop_on_fail>
	</run> 

<sequence name="GNUnet preinstallation and subversion" enabled="true">
    <run id="30" name="Install dependencies with yum : subversion">
          <command>sudo yum -y -t --nogpgcheck install</command> 
          <arguments>subversion</arguments> 
          <timeout>0</timeout> 
          <expected_return_code>0</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>false</stop_on_fail>
    </run>
    <run id="31" name="Download GNUnet svn certificate">
          <command>wget --no-check-certificate</command> 
          <arguments>https://gnunet.org/svn/gnunet-planetlab/gplmt/contrib/gnunet-svn-cert</arguments> 
          <timeout>0</timeout> 
          <expected_return_code>-1</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>false</stop_on_fail>
    </run> 
    <run id="32" name="Install GNUnet svn certificate">
          <command>mkdir .subversion; mkdir .subversion/auth; mkdir .subversion/auth/svn.ssl.server; cp gnunet-svn-cert .subversion/auth/svn.ssl.server/2bd0c10624fe8b217987bb45f1ec55bf</command> 
          <arguments></arguments> 
          <timeout>0</timeout> 
          <expected_return_code>-1</expected_return_code>
          <expected_output></expected_output>
          <stop_on_fail>false</stop_on_fail>
    </run> 
   <!-- GNUnet preinstallation and subversion end -->       
</sequence>	

<sequence name="Install GNUnet from SVN" enabled="true">
	  <run id="131" name="Download GNUnet">
	        <command>svn checkout</command> 
	        <arguments> https://gnunet.org/svn/gnunet</arguments> 
	        <timeout>0</timeout> 
	        <expected_return_code>0</expected_return_code>
	        <expected_output></expected_output>
	        <stop_on_fail>true</stop_on_fail>
	  </run>
	  <run id="131" name="SVN up GNUnet">
	        <command>cd gnunet; svn up</command> 
	        <arguments></arguments> 
	        <timeout>0</timeout> 
	        <expected_return_code>0</expected_return_code>
	        <expected_output></expected_output>
	        <stop_on_fail>true</stop_on_fail>
	  </run>
	  <run id="132" name="Bootstrap GNUnet" enabled="true">
	        <command>cd gnunet; libtoolize; ./bootstrap</command> 
	        <arguments></arguments> 
	        <timeout>0</timeout> 
	        <expected_return_code>0</expected_return_code>
	        <expected_output></expected_output>
	        <stop_on_fail>true</stop_on_fail>
	  </run>
	  <run id="133" name="Configure GNUnet" enabled="true">
	        <command>cd gnunet; export LD_LIBRARY_PATH=/usr/local/lib; ./configure </command> 
	        <arguments>--prefix=$HOME/gnbuild --with-extractor=/usr/local  --with-curl=/usr/local --with-mysql=/usr/lib/mysql --enable-logging=verbose</arguments> 
	        <timeout>0</timeout> 
	        <expected_return_code>0</expected_return_code>
	        <expected_output></expected_output>
	        <stop_on_fail>true</stop_on_fail>
	  </run>
	  <run id="134" name="Install GNUnet">
	        <command>cd gnunet; export LD_LIBRARY_PATH=/usr/local/lib; make install</command>
	        <arguments> </arguments> 
	        <timeout>0</timeout> 
	        <expected_return_code>0</expected_return_code>
	        <expected_output></expected_output>
	        <stop_on_fail>true</stop_on_fail>
	  </run>
 </sequence>
 
 
 <sequence name="Postinstallation setup" enabled="true">
  <run id="141" name="Create GNUnet directory" enabled="true">
        <command>mkdir .gnunet; touch .gnunet/gnunet.conf</command> 
        <arguments></arguments> 
        <timeout>0</timeout> 
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>true</stop_on_fail>
  </run>
  <run id="142" name="Set GNUNET_PREFIX" enabled="true">
        <command>echo -e "export GNUNET_PREFIX=$HOME/gnbuild \n" >> ~/.bashrc</command> 
        <arguments></arguments> 
        <timeout>0</timeout> 
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>true</stop_on_fail>
  </run>
  <run id="143" name="Configure GNUnet" enabled="true">
        <command>echo -e "export PATH=$PATH:$GNUNET_PREFIX/bin \n" >> ~/.bashrc</command> 
        <arguments></arguments> 
        <timeout>0</timeout> 
        <expected_return_code>0</expected_return_code>
        <expected_output></expected_output>
        <stop_on_fail>true</stop_on_fail>
  </run>
</sequence>	    
</tasklist>
